version: '3.8'

services:
  # Брокер повідомлень
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pastudy-rabbitmq
    ports:
      - "5672:5672"   # Порт для AMQP (для коду)
      - "15672:15672" # Панель керування (guest/guest)
    restart: always

  # Фейковий SMTP сервер (заміна MailCrab на MailHog)
  mailhog:
    image: mailhog/mailhog
    container_name: pastudy-mailhog
    ports:
      - "1025:1025"   # SMTP порт (сюди шлемо листи з C#)
      - "8025:8025"   # Web UI (тут дивимось листи в браузері)
    restart: always